### ISSUE TITLE
Import Error Help Please.

### ISSUE THREAD

**Issue by LePetitNewbie** [BenBrostoff/draftfast#175]
Hi, I just started using Python and I was wondering if someone could tell me what am I doing wrong?

i keep getting this message everytime i try to run draftfast. I am a super novice. just started playing around with it. if anyone can point me towards a solution, it would be very helpful.

ImportError: cannot import name 'rules' from 'draftfast' (C:\Users\User1\PycharmProjects\pythonProject1\venv\lib\site-packages\draftfast\__init__.py)

Cheers

**Comment by BenBrostoff** [comment]
Hey @LePetitNewbie - what version of Python are you using? This should work in 3.6 - [that's what the unit tests run in](https://github.com/BenBrostoff/draftfast/runs/2396028523). I'm going to close this issue as this import is unit tested.
